### ISSUE TITLE
Feature Request: checkingTemplate

### ISSUE THREAD

**Issue by fab1o** [ondrejbase/babel-plugin-jsdoc-type-checker#1]
I understand that `checkingTemplate` is a way to customize the error message. It would be nice if the user could customize the error message based on:

1. Class or object name
2. Method name 
3. Method parameters
4. Parameter name in question
5. Expected parameter type
6. Argument value

Essentially, the user would like could have an error message that looks like this (just an example of one situation):

`"ClassName.methodName(param1, param2, [param3]) param1 expected an instance of Type but received a value"`

Concrete example:

```js
class MyClass {
    /**
    * @typechecked
    * @param {Number} x
    * @param {Number} y
    * @param {Number} [z=0]
    * @return {Number}
    */
   myMethod(x, y, z) { }
}

(new MyClass()).myMethod(1, null);
```
Error: 
```js
"MyClass.myMethod(x, y, [z]) y expected a Number but received null"
```

1. `MyClass`
2. `myMethod`
3. `x,y,[z]`
4. `y`
5. `Number`
6. `null`

To do that, either the plugin already has this logic built-in or `checkingTemplate` could accept a function that receives all the 6 required arguments above (given by this plugin) so the user could build their own message and spit out a string.

**Comment by ondrejbase** [comment]
Hi look at the new [`checkingTemplate`](https://github.com/ondrejbase/babel-plugin-jsdoc-type-checker#checkingtemplate) in 3.0.0 version. It's only missing "received a value" part, but this part is possible to implement now too. You can change `checkingTemplate` string – it's possible to use `\${paramName}` directly in the code of the `checkingTemplate`. But remember that `\${paramName}` can return a name enclosed into square brackets, you have to remove them before you use this variable as a value.
